import json
from functools import lru_cache
from pathlib import Path

from fastapi import APIRouter, HTTPException

from api.schemas.predict import (
    EntitiesResponse,
    EntityResultOut,
    EntitySpanOut,
    PredictRequest,
    PredictResponse,
    TaskResultOut,
)
from ml.inference.base import EntityPredictor, Predictor
from ml.inference.baseline import BaselinePredictor
from ml.inference.rules_ner import RulesEntityPredictor

router = APIRouter(prefix="/predict", tags=["predict"])

_BASELINE_MODEL_PATHS = {
    "intent": Path("models/baseline_intent_v1/model.joblib"),
    "urgency": Path("models/baseline_urgency_v1/model.joblib"),
    "sentiment": Path("models/baseline_sentiment_v1/model.joblib"),
    "emotion": Path("models/baseline_emotion_v1/model.joblib"),
}

# Winning transformer variant per task, per docs/m3-comparison-report.md's
# persisted test-split macro-F1 comparison (generated by
# scripts/generate_m3_report.py). Picked once here rather than re-decided
# per request, mirroring how train_baseline_*.py exports only the winning
# classical variant — update this alongside the report if a model is
# retrained. Note the report recommends the *baseline* as default for
# intent (transformer doesn't beat it) — this path stays wired so the
# model="transformer" flag still works as an explicit opt-in, per SPEC M3's
# accept criterion that the flag switches per request regardless of which
# one wins.
_TRANSFORMER_MODEL_DIRS = {
    "intent": Path("models/transformer_intent_distilbert-base-uncased_v1/final"),
    "urgency": Path("models/transformer_urgency_deberta-v3-small_v1/final"),
    "sentiment": Path("models/transformer_sentiment_distilbert-base-uncased_v1/final"),
    "emotion": Path("models/transformer_emotion_distilbert-base-uncased_v1/final"),
}


@lru_cache
def _get_baseline_predictor(task: str) -> BaselinePredictor:
    return BaselinePredictor(_BASELINE_MODEL_PATHS[task])


@lru_cache
def _get_transformer_predictor(task: str) -> Predictor:
    # Imported lazily so a baseline-only deployment never needs
    # transformers/torch installed (CLAUDE.md: model choice selected by
    # config/request flag, not code duplication — but the heavy import stays
    # opt-in).
    from ml.inference.transformer import TransformerPredictor

    return TransformerPredictor(_TRANSFORMER_MODEL_DIRS[task])


def _get_predictor(task: str, model: str) -> Predictor:
    try:
        if model == "transformer":
            return _get_transformer_predictor(task)
        return _get_baseline_predictor(task)
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=f"{model} {task} model not available; run `make eval` to export it first",
        ) from exc


def _predict(task: str, request: PredictRequest) -> PredictResponse:
    predictor = _get_predictor(task, request.model)
    results = predictor.predict(request.texts)
    return PredictResponse(
        results=[
            TaskResultOut(label=r.label, score=r.score, probabilities=r.probabilities)
            for r in results
        ]
    )


@router.post("/intent", response_model=PredictResponse)
def predict_intent(request: PredictRequest) -> PredictResponse:
    return _predict("intent", request)


@router.post("/urgency", response_model=PredictResponse)
def predict_urgency(request: PredictRequest) -> PredictResponse:
    return _predict("urgency", request)


@router.post("/sentiment", response_model=PredictResponse)
def predict_sentiment(request: PredictRequest) -> PredictResponse:
    """3-class: negative/neutral/positive (SPEC M5, transferred from
    tweet_eval). Drives the per-ticket trajectory computed by
    scripts/compute_sentiment_trajectories.py -- see
    ml/inference/sentiment_trajectory.py for how per-message results here
    turn into that aggregate."""
    return _predict("sentiment", request)


@router.post("/emotion", response_model=PredictResponse)
def predict_emotion(request: PredictRequest) -> PredictResponse:
    """4-class: anger/joy/optimism/sadness (SPEC M5, transferred from
    tweet_eval). Secondary per-message signal -- not part of the sentiment
    trajectory aggregate (see ml/inference/sentiment_trajectory.py)."""
    return _predict("emotion", request)


# The M4 rules-vs-model routing, computed by scripts/generate_m4_report.py
# from real gold-set eval runs (docs/m4-rules-vs-model-report.md) and
# written here alongside the report -- not hardcoded, so a re-run after a
# new gold set or a retrained model updates live routing with no code
# change. On this repo's gold set, rules currently wins 4 of 5 entity
# types; only AMOUNT routes to the model.
_ENTITY_ROUTING_PATH = Path("models/entity_routing_v1.json")


@lru_cache
def _get_rules_entity_predictor() -> RulesEntityPredictor:
    return RulesEntityPredictor()


@lru_cache
def _get_hybrid_entity_predictor(task: str) -> EntityPredictor:
    # Imported lazily, same reason as _get_transformer_predictor above: a
    # rules-only deployment never needs transformers/torch installed.
    from ml.inference.hybrid_ner import HybridEntityPredictor
    from ml.inference.token_classification import TokenClassificationPredictor

    routing_config = json.loads(_ENTITY_ROUTING_PATH.read_text(encoding="utf-8"))
    model_predictor = TokenClassificationPredictor(Path(routing_config["model_export_dir"]))
    return HybridEntityPredictor(
        _get_rules_entity_predictor(), model_predictor, routing_config["labels"]
    )


def _get_entity_predictor(task: str, model: str) -> EntityPredictor:
    # Unlike _get_predictor, "baseline" here (the rules extractor) has no
    # file to be missing -- RulesEntityPredictor() never raises
    # FileNotFoundError, so model="baseline" can never 503. "transformer"
    # actually returns the hybrid predictor (see _get_hybrid_entity_predictor):
    # the best available combination per the real comparison, not
    # necessarily pure model output. Can 503 if either the routing file
    # (scripts/generate_m4_report.py hasn't run yet) or the model export
    # it points at is missing.
    try:
        if model == "transformer":
            return _get_hybrid_entity_predictor(task)
        return _get_rules_entity_predictor()
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=f"{model} {task} model not available; run `make eval-ner` first",
        ) from exc


def _predict_entities(task: str, request: PredictRequest) -> EntitiesResponse:
    predictor = _get_entity_predictor(task, request.model)
    results = predictor.predict(request.texts)
    return EntitiesResponse(
        results=[
            EntityResultOut(
                entities=[
                    EntitySpanOut(
                        start=span.start,
                        end=span.end,
                        label=span.label,
                        text=span.text,
                        score=span.score,
                    )
                    for span in result.entities
                ],
                truncated=result.truncated,
            )
            for result in results
        ]
    )


@router.post("/entities", response_model=EntitiesResponse)
def predict_entities(request: PredictRequest) -> EntitiesResponse:
    """Pass `text_clean`, not raw text: this endpoint never cleans its
    input, so the returned `start`/`end` on every span are character
    offsets into exactly the string you sent, not into some internally
    re-cleaned copy of it (the offset contract every M4 component shares --
    see ml.inference.base.EntitySpan's docstring).

    `model="transformer"` returns the hybrid predictor's output, not pure
    model output: each entity type routes to whichever system
    docs/m4-rules-vs-model-report.md found actually wins it on the real
    gold set, computed from persisted eval runs rather than assumed."""
    return _predict_entities("entities", request)
