from functools import lru_cache
from pathlib import Path

from fastapi import APIRouter, HTTPException

from api.schemas.predict import PredictRequest, PredictResponse, TaskResultOut
from ml.inference.base import Predictor
from ml.inference.baseline import BaselinePredictor

router = APIRouter(prefix="/predict", tags=["predict"])

_BASELINE_MODEL_PATHS = {
    "intent": Path("models/baseline_intent_v1/model.joblib"),
    "urgency": Path("models/baseline_urgency_v1/model.joblib"),
}

# Winning transformer variant per task, per docs/m3-comparison-report.md's
# persisted test-split macro-F1 comparison (generated by
# scripts/generate_m3_report.py). Picked once here rather than re-decided
# per request, mirroring how train_baseline_*.py exports only the winning
# classical variant — update this alongside the report if a model is
# retrained. Note the report recommends the *baseline* as default for
# intent (transformer doesn't beat it) — this path stays wired so the
# model="transformer" flag still works as an explicit opt-in, per SPEC M3's
# accept criterion that the flag switches per request regardless of which
# one wins.
_TRANSFORMER_MODEL_DIRS = {
    "intent": Path("models/transformer_intent_distilbert-base-uncased_v1/final"),
    "urgency": Path("models/transformer_urgency_deberta-v3-small_v1/final"),
}


@lru_cache
def _get_baseline_predictor(task: str) -> BaselinePredictor:
    return BaselinePredictor(_BASELINE_MODEL_PATHS[task])


@lru_cache
def _get_transformer_predictor(task: str) -> Predictor:
    # Imported lazily so a baseline-only deployment never needs
    # transformers/torch installed (CLAUDE.md: model choice selected by
    # config/request flag, not code duplication — but the heavy import stays
    # opt-in).
    from ml.inference.transformer import TransformerPredictor

    return TransformerPredictor(_TRANSFORMER_MODEL_DIRS[task])


def _get_predictor(task: str, model: str) -> Predictor:
    try:
        if model == "transformer":
            return _get_transformer_predictor(task)
        return _get_baseline_predictor(task)
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=f"{model} {task} model not available; run `make eval` to export it first",
        ) from exc


def _predict(task: str, request: PredictRequest) -> PredictResponse:
    predictor = _get_predictor(task, request.model)
    results = predictor.predict(request.texts)
    return PredictResponse(
        results=[
            TaskResultOut(label=r.label, score=r.score, probabilities=r.probabilities)
            for r in results
        ]
    )


@router.post("/intent", response_model=PredictResponse)
def predict_intent(request: PredictRequest) -> PredictResponse:
    return _predict("intent", request)


@router.post("/urgency", response_model=PredictResponse)
def predict_urgency(request: PredictRequest) -> PredictResponse:
    return _predict("urgency", request)
