"""canonical schema

Revision ID: 0001
Revises:
Create Date: 2026-08-10 12:20:24.269791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("dataset", sa.String(), nullable=False),
        sa.Column("split", sa.String(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_index(
        "ix_eval_runs_task_started_at", "eval_runs", ["task", "started_at"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Enum("bitext", "twitter", name="ticket_source"), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("source", "external_id", name="tickets_source_external_id"),
    )
    op.create_index("ix_tickets_brand", "tickets", ["brand"], unique=False)
    op.create_index("ix_tickets_created_at", "tickets", ["created_at"], unique=False)
    op.create_index(op.f("ix_tickets_source"), "tickets", ["source"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("author_role", sa.Enum("customer", "agent", name="author_role"), nullable=False),
        sa.Column("text_raw", sa.String(), nullable=False),
        sa.Column("text_clean", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lang", sa.String(length=8), nullable=True),
        sa.Column("lang_confidence", sa.Float(), nullable=True),
        sa.Column("content_hash", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_messages_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("ticket_id", "seq", name="messages_ticket_id_seq"),
    )
    op.create_index("ix_messages_content_hash", "messages", ["content_hash"], unique=False)
    op.create_index("ix_messages_lang", "messages", ["lang"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("eval_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(ticket_id IS NOT NULL) OR (message_id IS NOT NULL)",
            name=op.f("ck_predictions_prediction_has_target"),
        ),
        sa.ForeignKeyConstraint(
            ["eval_run_id"],
            ["eval_runs.id"],
            name=op.f("fk_predictions_eval_run_id_eval_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_predictions_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_predictions_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index(
        "ix_predictions_task_model_version", "predictions", ["task", "model_version"], unique=False
    )
    op.create_index(
        "ix_predictions_ticket_task", "predictions", ["ticket_id", "task"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_predictions_ticket_task", table_name="predictions")
    op.drop_index("ix_predictions_task_model_version", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_messages_lang", table_name="messages")
    op.drop_index("ix_messages_content_hash", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_tickets_source"), table_name="tickets")
    op.drop_index("ix_tickets_created_at", table_name="tickets")
    op.drop_index("ix_tickets_brand", table_name="tickets")
    op.drop_table("tickets")
    op.drop_index("ix_eval_runs_task_started_at", table_name="eval_runs")
    op.drop_table("eval_runs")
    # ### end Alembic commands ###
    # Postgres ENUM types survive drop_table and must be dropped explicitly,
    # or a subsequent upgrade fails with "type already exists".
    postgresql.ENUM(name="author_role").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="ticket_source").drop(op.get_bind(), checkfirst=True)
