"""Regenerates docs/tokenization-comparison.md (M1 deliverable).

Compares spaCy's rule-based tokenizer against BPE (roberta-base) and
WordPiece (bert-base-uncased) subword tokenization on 20 curated gnarly
examples, pinned in tests/fixtures/gnarly_examples.json so this doc
regenerates without the full corpus. Downloads two small public tokenizer
vocabularies from the Hugging Face Hub on first run (cached after) — this is
NOT a paid API call, just static vocab files.

Run: uv run python scripts/compare_tokenization.py
"""

import json
import statistics
from pathlib import Path
from typing import Any

import spacy
from tokenizers import Tokenizer

from ml.data.cleaning import clean_text
from ml.data.masking import additional_special_tokens

ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PATH = ROOT / "tests" / "fixtures" / "gnarly_examples.json"
OUTPUT_PATH = ROOT / "docs" / "tokenization-comparison.md"


def _load_spacy_tokenizer() -> Any:
    nlp = spacy.load(
        "en_core_web_sm",
        exclude=["tagger", "parser", "ner", "lemmatizer", "attribute_ruler", "tok2vec"],
    )
    return nlp.tokenizer


def _load_bpe_tokenizer(*, with_specials: bool) -> Tokenizer:
    tok = Tokenizer.from_pretrained("roberta-base")
    if with_specials:
        tok.add_special_tokens(additional_special_tokens())
    return tok


def _load_wordpiece_tokenizer() -> Tokenizer:
    tok = Tokenizer.from_pretrained("bert-base-uncased")
    tok.add_special_tokens(additional_special_tokens())
    return tok


def _spacy_tokens(tokenizer: Any, text: str) -> list[str]:
    return [t.text for t in tokenizer(text)]


def _hf_tokens(tokenizer: Tokenizer, text: str) -> list[str]:
    return tokenizer.encode(text).tokens


def _fence(tokens: list[str]) -> str:
    escaped = [t.replace("|", "\\|").replace("\n", "\\n") for t in tokens]
    return "`" + "` `".join(escaped) + "`"


def main() -> None:
    examples = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))

    spacy_tok = _load_spacy_tokenizer()
    bpe_naive = _load_bpe_tokenizer(with_specials=False)
    bpe_registered = _load_bpe_tokenizer(with_specials=True)
    wordpiece = _load_wordpiece_tokenizer()

    rows: list[dict[str, Any]] = []
    for example in examples:
        cleaned = clean_text(example["text"])
        row = {
            "id": example["id"],
            "note": example["note"],
            "raw": example["text"],
            "cleaned": cleaned,
            "spacy": _spacy_tokens(spacy_tok, cleaned),
            "bpe_naive": _hf_tokens(bpe_naive, cleaned),
            "bpe_registered": _hf_tokens(bpe_registered, cleaned),
            "wordpiece": _hf_tokens(wordpiece, cleaned),
        }
        rows.append(row)
        print(f"[{row['id']:>2}/20] {row['note']}")

    avg = lambda key: statistics.mean(len(r[key]) for r in rows)  # noqa: E731

    lines: list[str] = []
    lines.append("# Tokenization comparison: spaCy vs BPE vs WordPiece")
    lines.append("")
    lines.append(
        "Generated by `scripts/compare_tokenization.py` from "
        "`tests/fixtures/gnarly_examples.json` (M1 deliverable, SPEC §4). "
        "Every example is run through `ml.data.cleaning.clean_text` first — "
        "these are the strings a model actually sees, not the raw tweets."
    )
    lines.append("")
    lines.append(
        "Four tokenizers compared: spaCy `en_core_web_sm` (rule-based + statistical), "
        "RoBERTa BPE **without** our mask tokens registered, RoBERTa BPE **with** "
        "`ml.data.masking.additional_special_tokens()` registered, and BERT WordPiece "
        "(also with special tokens registered)."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Tokenizer | Avg tokens / example | Inflation vs spaCy |")
    lines.append("|---|---|---|")
    spacy_avg = avg("spacy")
    for key, label in [
        ("spacy", "spaCy"),
        ("bpe_naive", "BPE (roberta-base, no specials)"),
        ("bpe_registered", "BPE (roberta-base, +specials)"),
        ("wordpiece", "WordPiece (bert-base-uncased, +specials)"),
    ]:
        a = avg(key)
        lines.append(f"| {label} | {a:.1f} | {a / spacy_avg:.2f}x |")
    lines.append("")

    lines.append("## Per-example tokens")
    lines.append("")
    for row in rows:
        lines.append(f"### {row['id']}. {row['note']}")
        lines.append("")
        lines.append(f"- raw: `{row['raw']}`")
        lines.append(f"- cleaned: `{row['cleaned']}`")
        lines.append("")
        lines.append("| Tokenizer | Count | Tokens |")
        lines.append("|---|---|---|")
        lines.append(f"| spaCy | {len(row['spacy'])} | {_fence(row['spacy'])} |")
        lines.append(
            f"| BPE (no specials) | {len(row['bpe_naive'])} | {_fence(row['bpe_naive'])} |"
        )
        lines.append(
            f"| BPE (+specials) | {len(row['bpe_registered'])} | {_fence(row['bpe_registered'])} |"
        )
        lines.append(
            f"| WordPiece (+specials) | {len(row['wordpiece'])} | {_fence(row['wordpiece'])} |"
        )
        lines.append("")

    lines.append("## Analysis")
    lines.append("")
    lines.append(
        "**Mask-token survival.** In example 1, naive BPE fragments `<URL>` into "
        "3 subword pieces (`<`, `URL`, `>`); registering "
        "`additional_special_tokens()` collapses it to the single atomic token "
        "`<URL>` — this is why M3's tokenizer setup must call "
        "`add_special_tokens()` with that exact list before fine-tuning, or the "
        "model trains on fragments of our own mask vocabulary instead of a "
        "stable token. WordPiece shows the same fix cleanly; RoBERTa's "
        "byte-level pre-tokenizer occasionally emits a stray leading-space "
        "token immediately before an added token (see the `Ġ` before `<URL>` "
        "in example 1, and before both `<USER>` in example 15) that WordPiece "
        "does not — a real quirk of byte-level BPE, not a bug in our cleaning. "
        "Notably, spaCy's tokenizer *also* has no built-in notion of our mask "
        "tokens and splits them into `<`, `USER`/`URL`/etc., `>` just like "
        "naive BPE (example 1) — a from-scratch spaCy pipeline would need its "
        "own `tokenizer.add_special_case()` rules to treat them atomically."
    )
    lines.append("")
    lines.append(
        "**`<EMOJI:...>` tokens never survive.** Unlike the four fixed mask "
        "tokens, emoji tokens are open-vocabulary (`<EMOJI:red_heart>`, "
        "`<EMOJI:thumbs_up_medium_skin_tone>`, ...) and cannot be pre-registered "
        "as a finite special-token list. Every tokenizer here fragments them "
        "into `<`, `EMOJI`, `:`, the name pieces, and `>` (examples 4, 11, 20). "
        "If a future module needs emoji as a single semantic unit, that "
        "requires a dedicated pre-tokenizer step, not `additional_special_tokens`."
    )
    lines.append("")
    lines.append(
        "**Hashtags** (examples 6, 20) split at the `#` under all three "
        "tokenizers — spaCy's rule-based tokenizer treats `#` as its own "
        "punctuation token just like BPE/WordPiece do (`#`, `fail`), so none "
        "of the three preserve `#fail` as a single unit. If topic/keyword "
        "features ever need whole hashtags (a plausible M7 input), that's a "
        "custom pre-tokenization rule for every tokenizer here, not something "
        "any of them do out of the box."
    )
    lines.append("")
    lines.append(
        '**Elongations** (example 3, "sooooooo") are already capped to 3 '
        "repeats by `collapse_repeats` before tokenization, so none of the "
        "tokenizers see the original 7-character run — this is deliberate "
        "cleaning-pipeline behavior, not a tokenizer difference, but it's why "
        "the elongation doesn't blow up subword counts here."
    )
    lines.append("")
    lines.append(
        "**Contractions** (example 8) — all three tokenizers split at the "
        "apostrophe, but disagree on where the word boundary falls: spaCy "
        "splits `can't` into `ca` + `n't` (a linguistic split matching the "
        'underlying "can" + "not"), BPE keeps `can` whole and splits off '
        "`'t`, and WordPiece splits furthest — `can` + `'` + `t` as three "
        'separate pieces. Neither is "more correct"; they\'re solving '
        "different problems (linguistic units vs. compression), but it means "
        'a feature computed by counting "words" gives three different '
        "answers depending on which tokenizer produced it."
    )
    lines.append("")
    lines.append(
        "**OOV subword explosion.** Misspellings and slang (examples 9, 12, "
        '19 — "recieved", "damgaed", "lmaooo") inflate subword counts the '
        "most: BPE/WordPiece fall back to short, sometimes single-character "
        "pieces for text far from their pretraining distribution, while spaCy "
        "still emits one token per whitespace-delimited word regardless of "
        "spelling. This is the concrete evidence for why a subword vocabulary "
        "tolerates messy real-world text better than a fixed word-level "
        "vocabulary would: a classical bag-of-words pipeline treats "
        '"recieved" as pure out-of-vocabulary noise, while BPE/WordPiece '
        "decompose it into pieces seen during pretraining and still produce a "
        "usable representation."
    )
    lines.append("")
    lines.append(
        f"**Token-count inflation**, averaged across all 20 examples: BPE "
        f"without specials runs {avg('bpe_naive') / spacy_avg:.2f}x spaCy's "
        f"token count, dropping to {avg('bpe_registered') / spacy_avg:.2f}x once "
        f"mask tokens are registered; WordPiece lands at "
        f"{avg('wordpiece') / spacy_avg:.2f}x. Registering the mask vocabulary "
        f"is a measurable, not just cosmetic, difference in sequence length — "
        f"and sequence length is exactly what M3's latency budget (SPEC §3) "
        f"has to pay for."
    )
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
