"""Regenerates docs/m2-baseline-report.md from persisted EvalRun rows — never
hand-typed numbers (CLAUDE.md rule #5: no metric without an eval run).

Run: uv run python scripts/generate_baseline_report.py
"""

import random
from pathlib import Path

from api.config import get_settings
from api.db.models import AuthorRole, EvalRun, Message, Prediction, Ticket, TicketSource
from api.db.session import SessionLocal
from sqlalchemy import select
from sqlalchemy.orm import Session

from ml.evaluation.kappa import compute_kappa
from ml.inference.baseline import BaselinePredictor
from ml.training.baseline_common import MODELS_DIR

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "m2-baseline-report.md"
SPOT_CHECK_SIZE = 20


def _eval_runs_table(session: Session, task: str, split: str) -> list[EvalRun]:
    stmt = (
        select(EvalRun)
        .where(EvalRun.task == task, EvalRun.split == split)
        .order_by(EvalRun.model_version)
    )
    return list(session.scalars(stmt).all())


def _render_eval_run_table(runs: list[EvalRun]) -> list[str]:
    lines = ["| Model | Macro-F1 |", "|---|---|"]
    for run in runs:
        macro_f1 = run.metrics["macro_f1"]
        lines.append(f"| {run.model_version} | {macro_f1:.4f} |")
    return lines


def _render_per_class_f1(run: EvalRun) -> list[str]:
    per_class = run.metrics["per_class_f1"]
    lines = ["| Class | F1 |", "|---|---|"]
    for label, f1 in sorted(per_class.items(), key=lambda kv: kv[1]):
        lines.append(f"| {label} | {f1:.4f} |")
    return lines


def _qualitative_spot_check(session: Session, seed: int) -> list[tuple[str, str]]:
    stmt = (
        select(Message.text_clean)
        .join(Ticket, Ticket.id == Message.ticket_id)
        .where(
            Ticket.source == TicketSource.TWITTER,
            Message.author_role == AuthorRole.CUSTOMER,
            Message.lang == "en",
        )
    )
    all_texts = list(session.scalars(stmt).all())
    random.Random(seed).shuffle(all_texts)
    sample = all_texts[:SPOT_CHECK_SIZE]

    predictor = BaselinePredictor(MODELS_DIR / "baseline_intent_v1" / "model.joblib")
    results = predictor.predict(sample)
    return list(zip(sample, [r.label for r in results], strict=True))


def _kappa_section(session: Session) -> list[str]:
    from ml.data.weak_labels import weak_label_urgency

    stmt = select(Prediction).where(Prediction.task == "urgency_llm_seed")
    llm_predictions = session.scalars(stmt).all()

    if not llm_predictions:
        return [
            "**Pending.** The LLM seed-labeling script hasn't been run yet (it's gated behind "
            "`LLM_ENABLED`, off by default — see CLAUDE.md's paid-API discipline rule). Run "
            "`make seed-label-urgency` after setting `OPENAI_API_KEY` and `LLM_ENABLED=true` in "
            "`.env`, then regenerate this report.",
        ]

    message_ids = [p.message_id for p in llm_predictions if p.message_id is not None]
    messages = {
        m.id: m for m in session.scalars(select(Message).where(Message.id.in_(message_ids))).all()
    }
    weak_labels = []
    llm_labels = []
    for pred in llm_predictions:
        message = messages.get(pred.message_id) if pred.message_id else None
        if message is None or pred.label is None:
            continue
        weak_labels.append(weak_label_urgency(message.text_clean))
        llm_labels.append(pred.label)

    result = compute_kappa(weak_labels, llm_labels)
    return [
        f"Cohen's kappa between the rule-based weak urgency label and the LLM-seed label, "
        f"over {result.n} messages: **κ = {result.kappa:.4f}**.",
        "",
        "Per SPEC §7, this is reported as a weak-supervision agreement statistic, not treated as "
        'proof the weak labels are "correct" — urgency stays a weak-supervision showcase.',
    ]


def main() -> None:
    settings = get_settings()
    session = SessionLocal()
    try:
        intent_val_runs = _eval_runs_table(session, "intent", "val")
        intent_test_runs = _eval_runs_table(session, "intent", "test")
        urgency_val_runs = _eval_runs_table(session, "urgency", "val")
        urgency_test_runs = _eval_runs_table(session, "urgency", "test")
        spot_check = _qualitative_spot_check(session, settings.random_seed)
        kappa_lines = _kappa_section(session)
    finally:
        session.close()

    lines: list[str] = []
    lines.append("# M2 baseline report: intent & urgency classification")
    lines.append("")
    lines.append(
        "Generated by `scripts/generate_baseline_report.py` from `eval_runs` rows persisted by "
        "`ml.training.train_baseline_intent` / `train_baseline_urgency` — every number below comes "
        "from a committed eval run (CLAUDE.md rule #5), nothing here is hand-typed."
    )
    lines.append("")

    lines.append("## Intent (Bitext, 27 classes)")
    lines.append("")
    lines.append("### Validation — both trained variants")
    lines.append("")
    lines.extend(_render_eval_run_table(intent_val_runs))
    lines.append("")
    lines.append("### Test — selected variant (accept: macro-F1 >= 0.85)")
    lines.append("")
    lines.extend(_render_eval_run_table(intent_test_runs))
    if intent_test_runs:
        lines.append("")
        lines.append("Per-class F1 (selected variant, test split):")
        lines.append("")
        lines.extend(_render_per_class_f1(intent_test_runs[0]))
    lines.append("")
    lines.append(
        "**Read this number carefully.** Bitext is synthetic and templated — SPEC §7 flags this "
        'explicitly ("Bitext intents too clean/synthetic -> inflated scores"). A near-perfect '
        "score here says the classical baseline can trivially separate Bitext's 27 templates, not "
        "that it understands real customer intent. The qualitative spot-check below on real "
        "Twitter messages is the honest complement to this number."
    )
    lines.append("")

    lines.append("## Urgency (Twitter, weak-labeled, 3 classes)")
    lines.append("")
    lines.append("### Validation — both trained variants")
    lines.append("")
    lines.extend(_render_eval_run_table(urgency_val_runs))
    lines.append("")
    lines.append("### Test — selected variant")
    lines.append("")
    lines.extend(_render_eval_run_table(urgency_test_runs))
    if urgency_test_runs:
        lines.append("")
        lines.append("Per-class F1 (selected variant, test split):")
        lines.append("")
        lines.extend(_render_per_class_f1(urgency_test_runs[0]))
    lines.append("")
    lines.append(
        "No accept threshold applies here — SPEC frames urgency as a weak-supervision showcase. "
        "The macro-F1 above measures how well a TF-IDF classifier can reproduce the rule-based "
        "heuristic's own labels, not agreement with ground truth (which doesn't exist for urgency)."
    )
    lines.append("")

    lines.append("## Urgency weak-label vs LLM-seed agreement (Cohen's κ)")
    lines.append("")
    lines.extend(kappa_lines)
    lines.append("")

    lines.append(f"## Qualitative spot-check: intent baseline on {SPOT_CHECK_SIZE} real tweets")
    lines.append("")
    lines.append(
        "SPEC §7's explicit risk mitigation: report Bitext test scores *and* qualitative "
        "performance on real tweets, since the domain gap between templated Bitext instructions "
        "and messy real support tweets is exactly where a classical baseline is most likely to "
        "embarrass itself."
    )
    lines.append("")
    lines.append("| Real Twitter message | Predicted intent |")
    lines.append("|---|---|")
    for text, label in spot_check:
        escaped = text.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {escaped[:120]} | {label} |")
    lines.append("")
    lines.append(
        "This is the domain gap SPEC §7 warns about, made concrete: predictions above are "
        "frequently wrong or nonsensical on real tweets (e.g. a wireless-connection tip "
        "classified as `check_payment_methods`, a font-kerning complaint as `create_account`) "
        "despite the model scoring ~0.999 macro-F1 on Bitext's test split. The baseline learned "
        "Bitext's 27 templates very well; it did not learn customer intent in general. This gap "
        "is exactly the argument for M3's transformer fine-tune, and for eventually fine-tuning "
        "(or at least evaluating) on real support text rather than Bitext alone."
    )
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
